Repository openfun/arnold, pull requests merged in 2018-05, with the labels that each got.

#1 📄(LICENSE) switch to MIT Open Source license
  LICENSE
Labels: improvement

#2 🚀(script) add deploy and init utilities
  bin/deploy
  bin/init
Labels: improvement

#15 ⬆️(edxapp) upgrade edxapp to 1.0.2
  group_vars/all/main.yml
Labels: FUN, bug, easy pick, needs review

#21 🔥(util) remove unused .vault_pass.sh file
  .vault_pass.sh
Labels: improvement, needs review

#20 🐛(route) reactivate edxapp routes
  group_vars/all/openshift_routes.yml
Labels: bug, needs review

#22 🔥(secret) remove unused patient0 production secret
  group_vars/secret/patient0/production/richie/credentials.vault.yml
Labels: improvement, needs review

#41 ✨(elasticsearch) add ES common svc/dc
  bin/dev
  group_vars/all/main.yml
  group_vars/env_type/development.yml
  templates/openshift/common/dc/elasticsearch.yml.j2
  templates/openshift/common/svc/elasticsearch.yml.j2
  templates/openshift/richie/dc/richie.yml.j2
  templates/openshift/richie/job/regenerate_indexes.yml.j2
Labels: feature

#42 Customize settings for patient0 demo
  templates/configmap/edxapp-cms/settings.yml.j2
  templates/configmap/edxapp-lms/settings.yml.j2
Labels: FUN, feature
