Repository openfun/arnold, pull requests merged in 2018-07, with the labels that each got.

#72 ✨(playbook) add apps metadata from group_vars
  .gitignore
  VERSION
  ansible.cfg
  plugins/filter/merge.py
  requirements/pip-requirements.txt
  tasks/set_vars.yml
Labels: FUN, feature

#82 🐛(plugin) add new key support for the merge filter
  plugins/filter/merge.py
  tests/units/plugins/filter/test_merge.py
Labels: bug, critical

#83 Add openshift to circleci
  .circleci/config.yml
  bin/_config.sh
  env.d/development
  group_vars/env_type/development.yml
Labels: FUN, feature, needs review

#80 ✨(secret) make secrets app-specific
  apps/_common/templates/secret/env_vars.yml.j2
  create_secrets.yml
  group_vars/customer/patient0/development/secrets/edxapp.vault.yml
  group_vars/customer/patient0/development/secrets/richie.vault.yml
  group_vars/secret/credentials.dist.yml
  plugins/lookup/apps.py
  tasks/create_app_secrets.yml
Labels: feature, needs review

#85 🎨(scripts) improve OpenShift's env setting
  .circleci/config.yml
  bin/_config.sh
  bin/ansible-playbook
  bin/bootstrap
  bin/deploy
  bin/entrypoint
  bin/init
  bin/lint
  bin/pytest
  bin/switch
Labels: FUN, improvement, needs review

#87 🔥(vars) remove legacy template paths
  group_vars/all/main.yml
  group_vars/all/openshift_routes.yml
  group_vars/customer/hello/main.yml
  group_vars/env_type/development.yml
  group_vars/env_type/feature.yml
Labels: FUN, improvement, needs review

#86 👷(circle) fix & improve bootstrap test
  .circleci/config.yml
  group_vars/env_type/ci.yml
Labels: FUN, bug
