Repository openfun/arnold, pull requests merged in 2018-06, with the labels that each got.

#43 👷(tests) add CircleCI
  .circleci/config.yml
  README.md
  VERSION
  bin/entrypoint
Labels: critical, feature, needs review

#50 Add secrets versioning
  docs/developer_guide/secrets.md
  docs/index.md
  group_vars/all/main.yml
  templates/openshift/common/dc/mongodb.yml.j2
  templates/openshift/common/dc/mysql.yml.j2
  templates/openshift/common/dc/postgresql.yml.j2
  templates/openshift/common/secret/env_vars.yml.j2
  templates/openshift/edxapp/dc/cms.yml.j2
  templates/openshift/edxapp/dc/lms.yml.j2
  templates/openshift/edxapp/job/collectstatic_cms.yml.j2
  templates/openshift/edxapp/job/collectstatic_lms.yml.j2
  templates/openshift/edxapp/job/db_migrate.yml.j2
  templates/openshift/edxapp/job/load_fixtures.yml.j2
  templates/openshift/richie/dc/richie.yml.j2
  templates/openshift/richie/job/collectstatic.yml.j2
  templates/openshift/richie/job/db_migrate.yml.j2
  templates/openshift/richie/job/regenerate_indexes.yml.j2
Labels: FUN, feature, needs review

#37 ✅(lint) Add lint
  .circleci/config.yml
  .gitlab-ci.yml
  Dockerfile
  VERSION
  bin/_config.sh
  bin/ansible-playbook
  bin/build
  bin/deploy
  bin/dev
  bin/entrypoint
  bin/init
  bin/lint
  bin/run
  create_object.yml
  create_objects.yml
  create_project.yml
  deploy.yml
  docs/developer_guide/continous_integration.md
  docs/developer_guide/index.md
  docs/index.md
  load_fixtures.yml
  requirements/apt-packages.txt
  requirements/pip-requirements.txt
Labels: feature, improvement

#58 Feature/fix bin dev
  bin/dev
Labels: bug, critical

#57 ✨(job) ease job restart
  bin/job
  create_object.yml
  deploy.yml
  group_vars/all/main.yml
  templates/openshift/edxapp/job/collectstatic_cms.yml.j2
  templates/openshift/edxapp/job/collectstatic_lms.yml.j2
  templates/openshift/edxapp/job/db_migrate.yml.j2
  templates/openshift/edxapp/job/load_fixtures.yml.j2
  templates/openshift/richie/job/collectstatic.yml.j2
  templates/openshift/richie/job/db_migrate.yml.j2
  templates/openshift/richie/job/regenerate_indexes.yml.j2
Labels: feature, needs review

#64 feature/improve vars setting
  create_acme.yml
  create_config.yml
  create_object.yml
  create_project.yml
  create_secrets.yml
  delete_project.yml
  deploy.yml
  init_project.yml
  load_fixtures.yml
  tasks/set_vars.yml
Labels: FUN, feature, improvement

#67 🎨(playbook) Create bootstrap playbook #55
  README.md
  bin/bootstrap
  bootstrap.yml
  docs/developer_guide/getting_started.md
  docs/developer_guide/playbooks.md
  docs/installation/install.md
Labels: FUN, improvement

#68 Allow application filtering to select apps to work on
  tasks/set_vars.yml
Labels: feature
