Repository openfun/arnold, pull requests merged in 2018-12, with the labels that each got.

#176 🐛(forum) encode mongodb password in forum application
  apps/forum/templates/app/dc.yml.j2
  apps/forum/templates/app/job_01_init_index.yml.j2
  apps/forum/templates/app/secret.yml.j2
Labels: bug

#182 ✨(ci) configure ci to deploy docker images on docker hub
  .circleci/config.yml
Labels: FUN, feature

#192 ♻️ (ip) remove default cluster ip configuration
  apps/edxapp/templates/mongodb/ep.yml.j2
  apps/edxapp/templates/mysql/ep.yml.j2
  apps/forum/templates/mongodb/ep.yml.j2
  apps/marsha/templates/postgresql/ep.yml.j2
  apps/richie/templates/postgresql/ep.yml.j2
  group_vars/all/main.yml
  group_vars/env_type/preprod.yml
  group_vars/env_type/production.yml
  requirements/pip-requirements.txt
Labels: improvement

#193 🐛(routes) fix unexpected route deletion
  tasks/delete_app.yml
  tasks/deploy_patch_route.yml
Labels: FUN, bug, critical

#196 ♻️(databases) migrate databases settings into app's settings file
  apps/edxapp/vars/settings.yml
  apps/forum/vars/settings.yml
  apps/marsha/vars/settings.yml
  apps/richie/vars/settings.yml
  tasks/create_app_database_vault.yml
Labels: improvement

#197 🔖(alpha) bump version to 1.0.0-alpha.1
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#206 🔖(patch) bump release to 1.0.0-alpha.2
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#211 🐛(htpasswd) prevent new generation if file already exists
  CHANGELOG.md
  tasks/create_app_htpasswd.yml
Labels: bug, needs review

#212 🔖(patch) bump release to 1.0.0-alpha.3
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#200 ✨(edxapp) add internationalization job
  CHANGELOG.md
  apps/edxapp/templates/_volumes/locale.yml.j2
  apps/edxapp/templates/cms/_dc_base.yml.j2
  apps/edxapp/templates/cms/job_01_internationalization.yml.j2
  apps/edxapp/templates/cms/job_02_collectstatic.yml.j2
  apps/edxapp/templates/cms/job_05_db_migrate.yml.j2
  apps/edxapp/templates/cms/job_06_load_fixtures.yml.j2
  apps/edxapp/templates/cms/secret_transifex.yml.j2
  apps/edxapp/templates/lms/job_03_collectstatic.yml.j2
  apps/edxapp/templates/lms/job_04_db_migrate.yml.j2
  apps/edxapp/vars/all/main.yml
  apps/edxapp/vars/vault/main.yml.j2
Labels: feature

#213 ⚡️(edxapp) improve celery workers DC name
  CHANGELOG.md
  apps/edxapp/templates/cms/_dc_base.yml.j2
Labels: improvement, needs review

#215 🔖(patch) bump release to 1.0.0-alpha.4
  CHANGELOG.md
  VERSION
Labels: FUN
