Repository openfun/arnold, pull requests merged in 2019-11, with the labels that each got.

#391 🐛(marsha) test if sentry is defined before setting in secret
  CHANGELOG.md
  apps/marsha/templates/services/app/secret.yml.j2
Labels: bug

#395 ✨(redis) create a config map to manage redis configuration
  CHANGELOG.md
  apps/redis/templates/services/app/configs/app.conf.j2
  apps/redis/templates/services/app/dc.yml.j2
Labels: feature

#394 ♻️(richie) allow deactivating static/media volumes
  CHANGELOG.md
  apps/richie/templates/services/app/dc.yml.j2
  apps/richie/templates/services/app/job_01_collectstatic.yml.j2
  apps/richie/templates/services/app/job_04_bootstrap_elasticsearch.yml.j2
  apps/richie/templates/services/nginx/configs/richie.conf.j2
  apps/richie/templates/services/nginx/dc.yml.j2
  apps/richie/templates/volumes/media.yml.j2
  apps/richie/templates/volumes/static.yml.j2
  apps/richie/vars/all/main.yml
Labels: improvement

#397 🔖(minor) bump release to 3.3.0
  CHANGELOG.md
  VERSION
Labels: improvement

#401 🔖(major) bump release to 4.0.0
  CHANGELOG.md
  VERSION
Labels: FUN
