Repository openfun/arnold, pull requests merged in 2019-05, with the labels that each got.

#310 ✨(plugins) allow application template override
  CHANGELOG.md
  filter_plugins/merge.py
  tests/units/plugins/filter/test_merge.py
Labels: feature, needs review

#312 🐛(playbook) fix display name for new projects
  CHANGELOG.md
  create_project.yml
Labels: bug, needs review

#314 ⚡️(richie) make app templates more generic
  CHANGELOG.md
  apps/richie/templates/services/app/dc.yml.j2
  apps/richie/templates/services/app/job_01_collectstatic.yml.j2
  apps/richie/templates/services/app/job_02_db_migrate.yml.j2
  apps/richie/templates/services/app/job_03_bootstrap_elasticsearch.yml.j2
  apps/richie/vars/all/main.yml
Labels: improvement, needs review

#315 🔖(minor) bump release to 2.1.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#318 ♻️(marsha) use volumes only in trashable environments
  CHANGELOG.md
  apps/marsha/templates/services/app/dc.yml.j2
  apps/marsha/templates/services/app/job_collectstatic.yml.j2
  apps/marsha/templates/volumes/media.yml.j2
  apps/marsha/templates/volumes/static.yml.j2
Labels: improvement, needs review

#320 ✨(marsha) add a _env file to marsha application
  CHANGELOG.md
  apps/marsha/templates/services/app/_env.yml.j2
  apps/marsha/templates/services/app/dc.yml.j2
Labels: improvement, needs review

#321 🔖(patch) bump release to 2.2.0
  CHANGELOG.md
  VERSION
Labels: FUN

#322 🔖(minor) bump release to 2.3.0
  CHANGELOG.md
  VERSION
Labels: FUN

#323 🔒(apps) increase length of secrets keys to 50
  CHANGELOG.md
  apps/learninglocker/vars/vault/main.yml.j2
  apps/marsha/vars/vault/main.yml.j2
  apps/richie/vars/vault/main.yml.j2
Labels: improvement

#324 ✨(richie) add a _env file to richie application
  CHANGELOG.md
  apps/richie/templates/services/app/_env.yml.j2
  apps/richie/templates/services/app/dc.yml.j2
Labels: improvement

#326 🔖(minor) bump release to 2.4.0
  CHANGELOG.md
  VERSION
Labels: feature
