Repository openfun/arnold, pull requests merged in 2019-02, with the labels that each got.

#245 👷(circleci) build a docker image on master
  .circleci/config.yml
  CHANGELOG.md
Labels: FUN, improvement

#246 ⚡️(playbook) require apps_filter to switch
  CHANGELOG.md
  deploy.yml
  docs/developer_guide/playbooks.md
  switch.yml
Labels: easy pick, improvement, needs review

#247 ⬆️(richie) upgrade to 1.0.0-beta.1
  CHANGELOG.md
  apps/richie/templates/app/dc.yml.j2
  apps/richie/templates/app/job_01_db_migrate.yml.j2
  apps/richie/templates/app/job_02_collectstatic.yml.j2
  apps/richie/templates/app/job_03_bootstrap_elasticsearch.yml.j2
  apps/richie/vars/all/main.yml
  group_vars/env_type/development.yml
Labels: FUN, easy pick, improvement, needs review

#249 ⚡️(edxapp) configure memcached default cache backend
  CHANGELOG.md
  apps/edxapp/templates/cms/_configs/settings.yml.j2
  apps/edxapp/templates/lms/_configs/settings.yml.j2
  apps/edxapp/vars/all/main.yml
Labels: improvement

#250 🔖(patch) bump release to 1.4.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#251 ✏️(changelog) fix typos
  CHANGELOG.md
Labels: FUN, improvement, needs review

#256 🔖(patch) bump release to 1.5.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#259 🔥(ci) remove obsolete GitLab CI configuration
  .gitlab-ci.yml
  CHANGELOG.md
Labels: easy pick, improvement, needs review

#264 🔖(patch) bump release to 1.5.1
  CHANGELOG.md
  VERSION
Labels: FUN, needs review
