Repository openfun/arnold, pull requests merged in 2019-03, with the labels that each got.

#266 ✨(learninglocker) create a volume dedicated to storage
  CHANGELOG.md
  apps/learninglocker/templates/_volumes/storage.yml.j2
  apps/learninglocker/templates/app/_dc_base.yml.j2
  apps/learninglocker/templates/app/job_storage.yml.j2
  apps/learninglocker/vars/all/main.yml
Labels: improvement

#271 🔖(patch) bump release to 1.6.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#278 ✨(richie) add support for extra dependencies installation
  .circleci/config.yml
  CHANGELOG.md
  apps/richie/templates/app/bc.yml.j2
  apps/richie/vars/all/main.yml
  group_vars/customer/eugene/ci/main.yml
Labels: feature, needs review

#279 🔖(patch) bump release to 1.7.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#282 🐛(richie) fix media routes
  CHANGELOG.md
  apps/richie/templates/nginx/_configs/richie.conf.j2
Labels: FUN, bug, easy pick

#283 🔧(pyup) switch to weekly updates
  .pyup.yml
  CHANGELOG.md
Labels: easy pick, improvement, needs review

#285 🔧(marsha) add DJANGO_AWS_S3_REGION_NAME variable in marsha secret
  CHANGELOG.md
  apps/marsha/templates/app/secret.yml.j2
  group_vars/customer/eugene/ci/secrets/marsha.vault.yml
  group_vars/customer/eugene/development/secrets/marsha.vault.yml
Labels: improvement, needs review
