Repository openfun/arnold, pull requests merged in 2019-01, with the labels that each got.

#217 🔖(patch) bump release to 1.0.0-alpha.5
  CHANGELOG.md
  VERSION
Labels: improvement

#219 🐛(changelog) add missing release diff link
  CHANGELOG.md
Labels: easy pick, improvement, needs review

#222 🐛(marsha) fix CloudFront variable namespace
  CHANGELOG.md
  apps/marsha/templates/app/dc.yml.j2
Labels: bug, critical, needs review

#225 🔖(patch) bump release to 1.0.0-alpha.6
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#226 👷(circle) check that the changelog has been filled
  .circleci/config.yml
  CHANGELOG.md
Labels: improvement

#227 ✨(edxapp) add support for extra dependencies
  CHANGELOG.md
  apps/edxapp/templates/cms/bc.yml.j2
  apps/edxapp/templates/lms/bc.yml.j2
  apps/edxapp/vars/all/main.yml
Labels: WIP, feature, needs review

#228 🔖(patch) bump release to 1.0.0-alpha.7
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#229 ✨(services) allow to define multiple services object
  CHANGELOG.md
  tasks/get_objects_for_app.yml
Labels: improvement

#232 ⬆️(patch) bump release to 1.0.0-alpha.8
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#234 🔖(patch) bump release to 1.0.0
  CHANGELOG.md
  VERSION
Labels: FUN

#240 ✨(marsha) configure LRS variable in secret
  CHANGELOG.md
  apps/marsha/templates/app/secret.yml.j2
  apps/marsha/vars/all/main.yml
  apps/marsha/vars/vault/main.yml.j2
Labels: FUN, improvement

#241 🐛(marsha) encode in base64 LRS variables in marsha's secret
  apps/marsha/templates/app/secret.yml.j2
Labels: bug

#242 🔖(patch) bump release to 1.3.0
  CHANGELOG.md
  VERSION
Labels: FUN
