Repository openfun/arnold, pull requests merged in 2019-12, with the labels that each got.

#403 🔖(minor) bump release to 4.1.0
  CHANGELOG.md
  VERSION
Labels: FUN

#404 🐛(redis-sentinel) fix command to fetch project's annotation
  apps/redis-sentinel/vars/all/main.yml
Labels: improvement

#405 🐛(learninglocker) Inject XAPI secret as environment variable in XAPI DC
  CHANGELOG.md
  apps/learninglocker/templates/services/xapi/dc.yml.j2
Labels: bug

#406 🔖(patch) bump release to 4.1.1
  CHANGELOG.md
  VERSION
Labels: FUN

#408 ✨(redis-sentinel) apply podAntiAffinity rules
  CHANGELOG.md
  apps/redis-sentinel/templates/services/app/svc.yml.j2
Labels: improvement

#414 🐛(forum) fix API key random generator
  CHANGELOG.md
  apps/forum/vars/vault/main.yml.j2
Labels: bug
