Repository openfun/arnold, pull requests merged in 2019-10, with the labels that each got.

#374 🔖(major) bump release to 3.0.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#377 ✨(apps) make HTTP basic auth configurable per app
  CHANGELOG.md
  apps/edxapp/templates/services/nginx/configs/cms.conf.j2
  apps/edxapp/templates/services/nginx/configs/lms.conf.j2
  apps/edxapp/templates/services/nginx/dc.yml.j2
  apps/edxapp/templates/services/nginx/secret.yml.j2
  apps/edxapp/vars/all/main.yml
  apps/marsha/templates/services/nginx/configs/marsha.conf.j2
  apps/marsha/templates/services/nginx/dc.yml.j2
  apps/marsha/templates/services/nginx/secret.yml.j2
  apps/marsha/vars/all/main.yml
  apps/richie/templates/services/nginx/configs/richie.conf.j2
  apps/richie/templates/services/nginx/dc.yml.j2
  apps/richie/templates/services/nginx/secret.yml.j2
  apps/richie/vars/all/main.yml
  group_vars/all/main.yml
  tasks/get_vault_for_app.yml
Labels: improvement, needs review

#378 🐛(htaccess) fix nginx DC for basic-auth-aware apps
  apps/edxapp/templates/services/nginx/dc.yml.j2
  apps/marsha/templates/services/nginx/dc.yml.j2
  apps/richie/templates/services/nginx/dc.yml.j2
Labels: bug, easy pick, needs review

#379 🔖(minor) bump release to 3.1.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#382 🐛(secrets) fix private docker registry task when checking if file exists
  CHANGELOG.md
  tasks/create_docker_registry_secrets.yml
Labels: bug

#383 🔖(patch) bump release to 3.1.1
  CHANGELOG.md
  VERSION
Labels: bug

#384 🌐(edxapp) generate theme translations
  CHANGELOG.md
  apps/edxapp/templates/services/cms/_bc_base.yml.j2
Labels: improvement, needs review

#385 🐛(edxapp) fix jobs image name when using custom theme
  CHANGELOG.md
  apps/edxapp/templates/services/cms/job_01_internationalization.yml.j2
  apps/edxapp/templates/services/cms/job_02_collectstatic.yml.j2
  apps/edxapp/templates/services/cms/job_05_db_migrate.yml.j2
  apps/edxapp/templates/services/cms/job_06_load_fixtures.yml.j2
  apps/edxapp/templates/services/lms/job_03_collectstatic.yml.j2
  apps/edxapp/templates/services/lms/job_04_db_migrate.yml.j2
Labels: bug, needs review

#387 🔖(minor) bump release to 3.2.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review
