Repository openfun/arnold, pull requests merged in 2019-06, with the labels that each got.

#327 ✏️(edxapp) fix badly named nginx location
  CHANGELOG.md
  apps/edxapp/templates/services/nginx/configs/lms.conf.j2
Labels: bug

#329 🐛(richie) allow X_FRAME_OPTIONS=SAMEORIGN setting
  CHANGELOG.md
  apps/richie/templates/services/app/_env.yml.j2
Labels: bug, needs review

#331 🔖(patch) bump release to 2.4.1
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#333 ⚡️(apps) increase healthchecks periodicity
  CHANGELOG.md
  apps/edxapp/templates/services/cms/_dc_base.yml.j2
  apps/edxapp/templates/services/memcached/dc.yml.j2
  apps/edxapp/templates/services/nginx/dc.yml.j2
  apps/forum/templates/services/app/dc.yml.j2
  apps/learninglocker/templates/services/nginx/dc.yml.j2
  apps/marsha/templates/services/app/dc.yml.j2
  apps/marsha/templates/services/nginx/dc.yml.j2
  apps/redis/templates/services/app/dc.yml.j2
  apps/richie/templates/services/app/dc.yml.j2
  apps/richie/templates/services/nginx/dc.yml.j2
  core_apps/redirect/templates/services/nginx/dc.yml.j2
Labels: improvement

#334 🔖(patch) bump release to 2.4.2
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#336 ⚡️(edxapp) decrease workers healthcheck frequency
  CHANGELOG.md
  apps/edxapp/templates/services/cms/_dc_base.yml.j2
  apps/edxapp/vars/all/main.yml
Labels: improvement, needs review

#337 ✨(playbook) ensure secrets exist before deploying
  CHANGELOG.md
  deploy.yml
  tasks/check_app_secrets.yml
Labels: improvement

#340 ✨(playbook) add clean up utility
  CHANGELOG.md
  bin/clean
  clean.yml
  tasks/clean_app_orphans.yml
  tasks/deploy_get_stamp_from_route.yml
  tasks/rollback_routes.yml
  tasks/switch_routes.yml
Labels: feature, needs review

#341 🔖(minor) bump release to 2.5.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#342 🚑(playbook) handle permission issues for secrets check
  CHANGELOG.md
  tasks/check_app_secrets.yml
Labels: bug, critical, needs review

#344 🔖(patch) bump release to 2.5.1
  CHANGELOG.md
  VERSION
Labels: FUN, needs review
