Repository openfun/arnold, pull requests merged in 2019-04, with the labels that each got.

#286 🔧(marsha) add DJANGO_CLOUDFRONT_DOMAIN variable in marsha secret
  CHANGELOG.md
  apps/marsha/templates/app/secret.yml.j2
  group_vars/customer/eugene/ci/secrets/marsha.vault.yml
  group_vars/customer/eugene/development/secrets/marsha.vault.yml
Labels: improvement

#287 🔖(patch) bump release to 1.8.0
  CHANGELOG.md
  VERSION
Labels: FUN

#291 🔖(patch) bump release to 1.8.2
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#292 🐛(richie) fix elasticsearch job by mounting the media volume
  CHANGELOG.md
  apps/richie/templates/app/job_03_bootstrap_elasticsearch.yml.j2
Labels: bug, critical

#293 🔖(patch) bump release to 1.8.3
  CHANGELOG.md
  VERSION
Labels: bug

#295 🐛(django) flag collectstatic jobs as "pre" deployment jobs
  CHANGELOG.md
  apps/edxapp/templates/cms/job_02_collectstatic.yml.j2
  apps/edxapp/templates/lms/job_03_collectstatic.yml.j2
  apps/marsha/templates/app/job_collectstatic.yml.j2
  apps/richie/templates/app/job_01_collectstatic.yml.j2
  apps/richie/templates/app/job_02_collectstatic.yml.j2
  apps/richie/templates/app/job_02_db_migrate.yml.j2
Labels: bug, critical, easy pick, needs review

#296 🔧(edxapp) add new volume to store CSV exports files
  CHANGELOG.md
  apps/edxapp/templates/_volumes/exports.yml.j2
  apps/edxapp/templates/cms/_dc_base.yml.j2
  apps/edxapp/templates/lms/_configs/settings.yml.j2
  apps/edxapp/vars/all/main.yml
Labels: bug, improvement, needs review

#297 🔖(minor) bump release to 1.9.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#299 🔧(richie) change Elasticsearch host setting name
  CHANGELOG.md
  apps/richie/templates/app/dc.yml.j2
  apps/richie/templates/app/job_03_bootstrap_elasticsearch.yml.j2
Labels: FUN

#302 ➕(core) add jq/yq utilities
  CHANGELOG.md
  Dockerfile
  requirements.txt
Labels: improvement, needs review

#304 🔖(minor) bump release to 1.10.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review
