Repository openfun/arnold, pull requests merged in 2020-01, with the labels that each got.

#421 🐛 (learninglocker) Fix versioned vault file for eugene/development
  CHANGELOG.md
  group_vars/customer/eugene/development/secrets/learninglocker.vault.yml
Labels: bug

#420 🐛 (edxapp) fix MONGODB_HOST in eugene/development configuration
  CHANGELOG.md
  group_vars/customer/eugene/development/configs/edxapp/cms/settings.yml.j2
  group_vars/customer/eugene/development/configs/edxapp/lms/settings.yml.j2
Labels: bug

#422 📝 (readme) update oc version to use
  CHANGELOG.md
  README.md
Labels: improvement, needs review

#423 🐛 (script:dev) fix local ip detection
  CHANGELOG.md
  bin/dev
Labels: bug, needs review

#424 🔧(edxapp) configure routing timeout
  CHANGELOG.md
  apps/edxapp/templates/services/nginx/configs/cms.conf.j2
  apps/edxapp/templates/services/nginx/configs/lms.conf.j2
  apps/edxapp/templates/services/nginx/route_cms.yml.j2
  apps/edxapp/templates/services/nginx/route_lms.yml.j2
  apps/edxapp/templates/services/nginx/route_preview.yml.j2
  apps/edxapp/vars/all/main.yml
Labels: improvement

#428 🔖(minor) bump release to 4.5.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#429 :bug: (edxec) add edxec to eugene/development apps list
  CHANGELOG.md
  group_vars/customer/eugene/development/main.yml
Labels: bug, needs review

#431 🐛(edxapp) declare an lms queue in the cms celery queues
  CHANGELOG.md
  apps/edxapp/templates/services/cms/configs/settings.yml.j2
Labels: bug

#434 🐛(playbook) avoid downtime during switch or rollback
  CHANGELOG.md
  tasks/rollback_routes.yml
  tasks/switch_route.yml
  tasks/switch_routes.yml
Labels: bug, needs review

#435 🐛(playbook) improve delete_previous playbook behaviour on k8s api fai…
  CHANGELOG.md
  tasks/delete_app_objects_kind.yml
Labels: bug, needs review

#437 🚨(playbook) use the k8s_info module instead k8s_facts
  CHANGELOG.md
  create_redirect.yml
  delete_project.yml
  tasks/check_app_secrets.yml
  tasks/clean_app_orphans.yml
  tasks/create_app_builds.yml
  tasks/delete_app_objects_kind.yml
  tasks/deploy_get_stamp_from_route.yml
  tasks/manage_app.yml
  tasks/run_job.yml
Labels: improvement, needs review

#436 🚸(playbook) disallow switching if next stack is not deployed
  .circleci/config.yml
  CHANGELOG.md
  tasks/switch_routes.yml
Labels: improvement, needs review

#439 🚨(playbook) remove deprecation warnings
  CHANGELOG.md
  tasks/create_app_secrets.yml
  tasks/get_objects_for_app.yml
Labels: bug, needs review

#438 ✨(flower) create a flower application to monitor celery
  CHANGELOG.md
  apps/flower/templates/services/app/_env.yml.j2
  apps/flower/templates/services/app/configs/celeryconfig.py.j2
  apps/flower/templates/services/app/configs/project.py.j2
  apps/flower/templates/services/app/dc.yml.j2
  apps/flower/templates/services/app/svc.yml.j2
  apps/flower/templates/services/nginx/configs/flower.conf.j2
  apps/flower/templates/services/nginx/configs/healthcheck.conf.j2
  apps/flower/templates/services/nginx/dc.yml.j2
  apps/flower/templates/services/nginx/route_flower.yml.j2
  apps/flower/templates/services/nginx/svc.yml.j2
  apps/flower/tray.yml
  apps/flower/vars/all/main.yml
  apps/flower/vars/settings.yml
Labels: improvement

#441 🔖(minor) bump release to 4.7.0
  CHANGELOG.md
  VERSION
Labels: FUN

#451 🐛(playbook) fix JSON config file generation from jinja2 template
  CHANGELOG.md
  apps/hello/templates/services/app/configs/test.json.j2
  tasks/create_app_config.yml
Labels: bug, needs review

#447 ✨(apps) add elasticsearch application
  .circleci/config.yml
  CHANGELOG.md
  apps/elasticsearch/templates/services/app/configs/elasticsearch.yml.j2
  apps/elasticsearch/templates/services/app/configs/index-template.json.j2
  apps/elasticsearch/templates/services/app/configs/readiness-probe.sh.j2
  apps/elasticsearch/templates/services/app/configs/set-index-template.sh.j2
  apps/elasticsearch/templates/services/app/dc.yml.j2
  apps/elasticsearch/templates/services/app/job_set_index_template.yml.j2
  apps/elasticsearch/templates/services/app/svc-discovery.yml.j2
  apps/elasticsearch/templates/services/app/svc.yml.j2
  apps/elasticsearch/tray.yml
  apps/elasticsearch/vars/all/main.yml
  apps/elasticsearch/vars/settings.yml
  bin/ci-test-route
  bin/ci-test-service
  group_vars/customer/eugene/development/main.yml
  group_vars/customer/eugene/main.yml
  group_vars/env_type/ci.yml
  group_vars/env_type/development.yml
Labels: feature, needs review
