Repository openfun/arnold, pull requests merged in 2020-10, with the labels that each got.

#552 ✨(edxapp) allow to change pvc media name
  CHANGELOG.md
  apps/edxapp/templates/services/cms/_dc_base.yml.j2
  apps/edxapp/templates/services/cms/job_01_create_directories.yml.j2
  apps/edxapp/templates/services/cms/job_04_db_migrate.yml.j2
  apps/edxapp/templates/services/cms/job_05_load_fixtures.yml.j2
  apps/edxapp/templates/services/lms/job_03_db_migrate.yml.j2
  apps/edxapp/templates/services/nginx/dc.yml.j2
  apps/edxapp/templates/volumes/media.yml.j2
Labels: improvement

#554 ♻️(ci) stop pulling images anonymously
  .circleci/config.yml
Labels: FUN, improvement

#555 🔖(minor) bump release to 5.17.0
  CHANGELOG.md
  VERSION
Labels: FUN

#559 🐛(elasticsearch) fix YAML syntax error
  CHANGELOG.md
  apps/elasticsearch/templates/services/app/job_03_create_admin_user.yml.j2
Labels: bug, needs review
