Repository openfun/arnold, pull requests merged in 2020-05, with the labels that each got.

#503 ✨(marsha) allow to set unlimited secrets
  CHANGELOG.md
  apps/marsha/templates/services/app/secret.yml.j2
Labels: improvement

#505 ✨(marsha) create custom settings module
  CHANGELOG.md
  apps/marsha/templates/services/app/_dc_base.yml.j2
  apps/marsha/templates/services/app/configs/__init__.py.j2
  apps/marsha/templates/services/app/configs/settings.py.j2
Labels: improvement

#506 ✨(redis-sentinel) allow to disable persistence
  CHANGELOG.md
  apps/redis-sentinel/templates/services/app/svc.yml.j2
  apps/redis-sentinel/vars/all/main.yml
Labels: improvement

#507 🔖(minor) bump release to 5.9.0
  CHANGELOG.md
  VERSION
Labels: FUN

#510 🔖(minor) bump release to 5.10.0
  CHANGELOG.md
  VERSION
Labels: improvement

#513 🔖(minor) bump release to 5.11.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#516 🐛(core) fix openshift-acme role permissions
  CHANGELOG.md
  core_apps/acme/templates/services/app/role.yml.j2
Labels: bug, needs review
