Repository openfun/arnold, pull requests merged in 2020-04, with the labels that each got.

#469 ✨(apps) add nextcloud application
  .circleci/config.yml
  CHANGELOG.md
  apps/nextcloud/templates/services/app/_env.yml.j2
  apps/nextcloud/templates/services/app/bc.yml.j2
  apps/nextcloud/templates/services/app/configs/config.php.j2
  apps/nextcloud/templates/services/app/cronjob_cron.yml.j2
  apps/nextcloud/templates/services/app/dc.yml.j2
  apps/nextcloud/templates/services/app/is.yml.j2
  apps/nextcloud/templates/services/app/job_01_install.yml.j2
  apps/nextcloud/templates/services/app/secret.yml.j2
  apps/nextcloud/templates/services/app/svc.yml.j2
  apps/nextcloud/templates/services/nginx/configs/healthcheck.conf.j2
  apps/nextcloud/templates/services/nginx/configs/nextcloud.conf.j2
  apps/nextcloud/templates/services/nginx/dc.yml.j2
  apps/nextcloud/templates/services/nginx/route.yml.j2
  apps/nextcloud/templates/services/nginx/secret.yml.j2
  apps/nextcloud/templates/services/nginx/svc.yml.j2
  apps/nextcloud/templates/services/postgresql/dc.yml.j2
  apps/nextcloud/templates/services/postgresql/ep.yml.j2
  apps/nextcloud/templates/services/postgresql/secret.yml.j2
  apps/nextcloud/templates/services/postgresql/svc.yml.j2
  apps/nextcloud/templates/volumes/install.yml.j2
  apps/nextcloud/tray.yml
  apps/nextcloud/vars/all/main.yml
  apps/nextcloud/vars/settings.yml
  apps/nextcloud/vars/vault/main.yml.j2
  group_vars/customer/eugene/ci/main.yml
  group_vars/customer/eugene/ci/secrets/nextcloud.vault.yml
  group_vars/customer/eugene/development/main.yml
  group_vars/customer/eugene/development/secrets/nextcloud.vault.yml
  group_vars/customer/eugene/main.yml
  group_vars/env_type/ci.yml
Labels: FUN, WIP, feature

#479 ✨(apps) add nginx status endpoint in arnold applications
  CHANGELOG.md
  apps/ashley/templates/services/nginx/configs/healthcheck.conf.j2
  apps/ashley/vars/all/main.yml
  apps/edxapp/templates/services/nginx/configs/healthcheck.conf.j2
  apps/edxapp/vars/all/main.yml
  apps/edxec/templates/services/nginx/configs/healthcheck.conf.j2
  apps/edxec/vars/all/main.yml
  apps/flower/templates/services/nginx/configs/healthcheck.conf.j2
  apps/flower/vars/all/main.yml
  apps/learninglocker/templates/services/nginx/configs/healthcheck.conf.j2
  apps/learninglocker/vars/all/main.yml
  apps/marsha/templates/services/nginx/configs/healthcheck.conf.j2
  apps/marsha/vars/all/main.yml
  apps/nextcloud/templates/services/nginx/configs/healthcheck.conf.j2
  apps/nextcloud/vars/all/main.yml
  apps/richie/templates/services/nginx/configs/healthcheck.conf.j2
  apps/richie/vars/all/main.yml
Labels: feature, needs review

#481 🔧(nextcloud) remove app skeleton in BuildConfig
  apps/nextcloud/templates/services/app/bc.yml.j2
Labels: improvement

#487 🐛(edxapp) fix nginx collectstatic BC theme support
  CHANGELOG.md
  apps/edxapp/templates/services/nginx/bc_collectstatic.yml.j2
Labels: bug, critical, needs review

#473 Add etherpad application
  .circleci/config.yml
  CHANGELOG.md
  apps/etherpad/templates/services/app/_env.yml.j2
  apps/etherpad/templates/services/app/configs/settings.json.j2
  apps/etherpad/templates/services/app/dc.yml.j2
  apps/etherpad/templates/services/app/secret_env.yml.j2
  apps/etherpad/templates/services/app/secret_keys.yml.j2
  apps/etherpad/templates/services/app/svc.yml.j2
  apps/etherpad/templates/services/nginx/configs/etherpad.conf.j2
  apps/etherpad/templates/services/nginx/configs/healthcheck.conf.j2
  apps/etherpad/templates/services/nginx/dc.yml.j2
  apps/etherpad/templates/services/nginx/route.yml.j2
  apps/etherpad/templates/services/nginx/secret.yml.j2
  apps/etherpad/templates/services/nginx/svc.yml.j2
  apps/etherpad/templates/services/postgresql/dc.yml.j2
  apps/etherpad/templates/services/postgresql/ep.yml.j2
  apps/etherpad/templates/services/postgresql/secret.yml.j2
  apps/etherpad/templates/services/postgresql/svc.yml.j2
  apps/etherpad/tray.yml
  apps/etherpad/vars/all/main.yml
  apps/etherpad/vars/settings.yml
  apps/etherpad/vars/vault/main.yml.j2
  group_vars/customer/eugene/ci/secrets/etherpad.vault.yml
  group_vars/customer/eugene/development/main.yml
  group_vars/customer/eugene/development/secrets/etherpad.vault.yml
  group_vars/env_type/ci.yml
  group_vars/env_type/development.yml
Labels: feature, needs review

#490 🐛(nextcloud) use nextcloud image built by our BC in the Nginx InitContainer
  CHANGELOG.md
  apps/nextcloud/templates/services/nginx/dc.yml.j2
Labels: bug

#492 👷(circle) enable nextcloud hub dependency
  .circleci/config.yml
Labels: FUN

#494 🔧(learninglocker) improve pm2 logs configuration
  CHANGELOG.md
  apps/learninglocker/templates/services/app/configs/ecosystem.config.js.j2
  apps/learninglocker/templates/services/xapi/configs/ecosystem.config.js.j2
Labels: improvement, needs review

#495 ⚡️(etherpad) implement reliable health checks
  CHANGELOG.md
  apps/etherpad/templates/services/app/_env.yml.j2
  apps/etherpad/templates/services/app/dc.yml.j2
  apps/etherpad/vars/all/main.yml
Labels: improvement, needs review

#497 🔖(minor) bump release to 5.6.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#498 ✨(core) add support for generic ConfigMap templates
  CHANGELOG.md
  tasks/create_app_config.yml
  tasks/get_objects_for_app.yml
Labels: feature, needs review

#499 🔖(minor) bump release to 5.7.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#501 ♻️(marsha) split app services to isolate xapi requests
  CHANGELOG.md
  apps/marsha/templates/services/app/_dc_base.yml.j2
  apps/marsha/templates/services/app/dc_app.yml.j2
  apps/marsha/templates/services/app/dc_xapi.yml.j2
  apps/marsha/templates/services/app/svc_app.yml.j2
  apps/marsha/templates/services/app/svc_xapi.yml.j2
  apps/marsha/templates/services/nginx/configs/marsha.conf.j2
  apps/marsha/vars/all/main.yml
Labels: critical, improvement

#502 🔖(minor) bump release to 5.8.0
  CHANGELOG.md
  VERSION
Labels: FUN
