Repository openfun/arnold, pull requests merged in 2020-11, with the labels that each got.

#563 🐛(acme) fix priority type in CM
  CHANGELOG.md
  core_apps/acme/templates/services/app/cm.yml.j2
Labels: bug, needs review

#564 ✨(moodle) add application Moodlenet
  .circleci/config.yml
  CHANGELOG.md
  apps/moodlenet/templates/services/backend/_env.yml.j2
  apps/moodlenet/templates/services/backend/dc.yml.j2
  apps/moodlenet/templates/services/backend/secret.yml.j2
  apps/moodlenet/templates/services/backend/svc.yml.j2
  apps/moodlenet/templates/services/nginx/configs/healthcheck.conf.j2
  apps/moodlenet/templates/services/nginx/configs/moodlenet.conf.j2
  apps/moodlenet/templates/services/nginx/dc.yml.j2
  apps/moodlenet/templates/services/nginx/route.yml.j2
  apps/moodlenet/templates/services/nginx/secret.yml.j2
  apps/moodlenet/templates/services/nginx/svc.yml.j2
  apps/moodlenet/templates/services/postgresql/dc.yml.j2
  apps/moodlenet/templates/services/postgresql/ep.yml.j2
  apps/moodlenet/templates/services/postgresql/job_create_extension.yml.j2
  apps/moodlenet/templates/services/postgresql/secret.yml.j2
  apps/moodlenet/templates/services/postgresql/svc.yml.j2
  apps/moodlenet/templates/volumes/uploads.yml.j2
  apps/moodlenet/tray.yml
  apps/moodlenet/vars/all/main.yml
  apps/moodlenet/vars/settings.yml
  apps/moodlenet/vars/vault/main.yml.j2
  bin/ci-test-route
  group_vars/customer/eugene/ci/secrets/moodlenet.vault.yml
  group_vars/customer/eugene/development/main.yml
  group_vars/customer/eugene/development/secrets/moodlenet.vault.yml
  group_vars/env_type/ci.yml
  group_vars/env_type/development.yml
Labels: feature, needs review

#565 🔖(minor) bump release to 5.20.0
  CHANGELOG.md
  VERSION
Labels: FUN

#530 ✨(apps) choose to enable acme based on route prefix
  CHANGELOG.md
  apps/ashley/templates/services/nginx/route.yml.j2
  apps/edxapp/templates/services/nginx/route_cms.yml.j2
  apps/edxapp/templates/services/nginx/route_lms.yml.j2
  apps/edxapp/templates/services/nginx/route_preview.yml.j2
  apps/edxec/templates/services/nginx/route.yml.j2
  apps/etherpad/templates/services/nginx/route.yml.j2
  apps/flower/templates/services/nginx/route_flower.yml.j2
  apps/forum/templates/services/app/route.yml.j2
  apps/hello/templates/services/app/route.yml.j2
  apps/kibana/templates/services/nginx/route.yml.j2
  apps/learninglocker/templates/services/nginx/route.yml.j2
  apps/marsha/templates/services/nginx/route.yml.j2
  apps/moodlenet/templates/services/nginx/route.yml.j2
  apps/nextcloud/templates/services/nginx/route.yml.j2
  apps/richie/templates/services/nginx/route.yml.j2
  group_vars/all/main.yml
  group_vars/env_type/production.yml
Labels: WIP, improvement

#567 ✨(marsha) add a cronjob to stop unused live streaming
  CHANGELOG.md
  apps/marsha/templates/services/app/cronjob_check_live_state.yml.j2
Labels: improvement

#568 🔖(minor) bump release to 5.21.0
  CHANGELOG.md
  VERSION
Labels: FUN

#574 [edxapp] Set "Referer" header with "Origin" header when empty and release fix
  CHANGELOG.md
  VERSION
  apps/edxapp/templates/services/nginx/configs/lms.conf.j2
Labels: bug
