Repository openfun/arnold, pull requests merged in 2020-03, with the labels that each got.

#466 🐛(elasticsearch) fix elasticsearch configuration template
  CHANGELOG.md
  apps/elasticsearch/templates/services/app/configs/elasticsearch.yml.j2
Labels: bug, needs review

#474 🔖(minor) bump release to 5.2.0
  CHANGELOG.md
  VERSION
Labels: bug, improvement

#470 ✨(ashley) add app Ashley, the alternative discussion forum for OpenEdx
  .circleci/config.yml
  CHANGELOG.md
  apps/ashley/templates/services/app/_env.yml.j2
  apps/ashley/templates/services/app/dc.yml.j2
  apps/ashley/templates/services/app/job_01_collectstatic.yml.j2
  apps/ashley/templates/services/app/job_02_db_migrate.yml.j2
  apps/ashley/templates/services/app/secret.yml.j2
  apps/ashley/templates/services/app/svc.yml.j2
  apps/ashley/templates/services/nginx/configs/ashley.conf.j2
  apps/ashley/templates/services/nginx/configs/healthcheck.conf.j2
  apps/ashley/templates/services/nginx/dc.yml.j2
  apps/ashley/templates/services/nginx/route.yml.j2
  apps/ashley/templates/services/nginx/secret.yml.j2
  apps/ashley/templates/services/nginx/svc.yml.j2
  apps/ashley/templates/services/postgresql/dc.yml.j2
  apps/ashley/templates/services/postgresql/ep.yml.j2
  apps/ashley/templates/services/postgresql/secret.yml.j2
  apps/ashley/templates/services/postgresql/svc.yml.j2
  apps/ashley/templates/volumes/media.yml.j2
  apps/ashley/templates/volumes/static.yml.j2
  apps/ashley/tray.yml
  apps/ashley/vars/all/main.yml
  apps/ashley/vars/settings.yml
  apps/ashley/vars/vault/main.yml.j2
  group_vars/customer/eugene/ci/secrets/ashley.vault.yml
  group_vars/customer/eugene/development/main.yml
  group_vars/customer/eugene/development/secrets/ashley.vault.yml
  group_vars/customer/eugene/development/secrets/databases.vault.yml
  group_vars/env_type/ci.yml
  group_vars/env_type/development.yml
Labels: feature, needs review

#475 ✨(core) upgrade acme to v2 API
  CHANGELOG.md
  core_apps/acme/templates/services/app/cm_live.yml.j2
  core_apps/acme/templates/services/app/cm_staging.yml.j2
  core_apps/acme/templates/services/app/dpl.yml.j2
  core_apps/acme/templates/services/app/is.yml.j2
  core_apps/acme/templates/services/app/role.yml.j2
Labels: critical, improvement, needs review

#478 🔖(minor) bump release to 5.3.0
  CHANGELOG.md
  VERSION
Labels: bug, feature, improvement
