Repository openfun/arnold, pull requests merged in 2020-02, with the labels that each got.

#454 🔖(major) bump release to 5.0.0
  CHANGELOG.md
  VERSION
Labels: FUN

#457 ✅(scripts) add argument to ci-test-route to set the max retries
  .circleci/config.yml
  CHANGELOG.md
  bin/ci-test-route
Labels: improvement, needs review

#458 🐛(edxapp) fix image pull policy
  CHANGELOG.md
  apps/edxapp/templates/services/cms/_dc_base.yml.j2
  apps/edxapp/templates/services/cms/job_01_create_directories.yml.j2
  apps/edxapp/templates/services/cms/job_02_internationalization.yml.j2
  apps/edxapp/templates/services/cms/job_04_db_migrate.yml.j2
  apps/edxapp/templates/services/cms/job_05_load_fixtures.yml.j2
  apps/edxapp/templates/services/lms/job_03_db_migrate.yml.j2
Labels: FUN, bug

#463 🐛(edxapp) force to create staticfiles directory in bc_collectstatic template
  CHANGELOG.md
  apps/edxapp/templates/services/nginx/bc_collectstatic.yml.j2
Labels: bug

#464 🔖(minor) bump release to 5.1.0
  CHANGELOG.md
  VERSION
Labels: FUN
