Repository openfun/arnold, pull requests merged in 2020-07, with the labels that each got.

#526 🔖(minor) bump release to 5.13.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#527 🐛(core) exclude acme routes when looking for app routes
  CHANGELOG.md
  tasks/deploy_get_stamp_from_route.yml
Labels: bug

#528 🔖(patch) bump release to 5.13.1
  CHANGELOG.md
  VERSION
Labels: FUN
