Repository openfun/arnold, pull requests merged in 2020-08, with the labels that each got.

#535 ✨(richie) allow placing static files behind a CDN
  CHANGELOG.md
  apps/richie/templates/services/nginx/configs/richie.conf.j2
Labels: feature

#534 🐛(core) create only required acme issuer CM
  CHANGELOG.md
  core_apps/acme/templates/services/app/cm.yml.j2
  core_apps/acme/templates/services/app/cm_staging.yml.j2
Labels: bug, needs review

#539 🐛(edxapp) pin transifex-client version in edx i18n job
  CHANGELOG.md
  apps/edxapp/templates/services/cms/job_02_internationalization.yml.j2
Labels: bug

#540 🔖(patch) bump release to 5.14.1
  CHANGELOG.md
  VERSION
Labels: FUN
