Repository openfun/arnold, pull requests merged in 2021-09, with the labels that each got.

#683 🔖(minor) bump release to 6.2.0
  CHANGELOG.md
  VERSION
Labels: FUN

#685 🔖(minor) bump release to 6.3.0
  CHANGELOG.md
  VERSION
Labels: FUN

#687 🔧(project) replace pyup with renovate for dependencies updates
  .dockerignore
  .pyup.yml
  renovate.json
Labels: improvement

#689 🐛(project) fix renovate configuration
  renovate.json
Labels: bug, needs review

#688 ⬆️ (project) upgrade to python 3.9
  CHANGELOG.md
  Dockerfile
  requirements/production.txt
  tasks/set_vars.yml
Labels: improvement, needs review

#692 Add RBAC built-in support
  CHANGELOG.md
  apps/hello/templates/services/app/rbac-cluster-role-pod-reader.yml.j2
  apps/hello/templates/services/app/rbac-role-binding-pod-reader.yml.j2
  tasks/get_objects_for_app.yml
  tasks/manage_app.yml
Labels: feature, needs review

#693 🔖(minor) bump release to 6.4.0
  CHANGELOG.md
  VERSION
Labels: needs review, FUN
