Repository openfun/arnold, pull requests merged in 2021-03, with the labels that each got.

#630 ✨(marsha) add cronjob for management command check_harvested
  CHANGELOG.md
  apps/marsha/templates/services/app/cronjob_check_harvested.yml.j2
  apps/marsha/vars/all/main.yml
Labels: FUN

#631 🐛(edxapp) fix type error endpoint templates
  apps/edxapp/templates/services/mongodb/ep.yml.j2
  apps/edxapp/templates/services/mysql/ep.yml.j2
Labels: bug

#632 🎨(apps) fix code style in templates to improve readability
  CHANGELOG.md
  apps/ashley/templates/services/nginx/ingress.yml.j2
  apps/edxapp/templates/services/nginx/ingress_cms.yml.j2
  apps/edxapp/templates/services/nginx/ingress_lms.yml.j2
  apps/edxapp/templates/services/nginx/ingress_preview.yml.j2
  apps/edxec/templates/services/nginx/ingress.yml.j2
  apps/etherpad/templates/services/nginx/ingress.yml.j2
  apps/flower/templates/services/nginx/ingress_flower.yml.j2
  apps/forum/templates/services/app/ingress.yml.j2
  apps/hello/templates/services/app/ingress.yml.j2
  apps/kibana/templates/services/nginx/ingress.yml.j2
  apps/mailcatcher/templates/services/app/ingress.yml.j2
  apps/marsha/templates/services/nginx/ingress.yml.j2
  apps/richie/templates/services/nginx/ingress.yml.j2
  core_apps/acme/vars/all/main.yml
  core_apps/redirect/templates/services/nginx/_redirected_ingress.yml.j2
  group_vars/all/main.yml
Labels: improvement

#633 🔧(redis-sentinel) update redis-sentinel to be compatible with k8s
  apps/redis-sentinel/templates/services/app/svc.yml.j2
  apps/redis-sentinel/vars/all/main.yml
Labels: improvement, needs review

#636 ✨(marsha) add cronjob for management command check_live_idle
  CHANGELOG.md
  apps/marsha/templates/services/app/cronjob_check_live_idle.yml.j2
  apps/marsha/vars/all/main.yml
Labels: feature

#638 🔖(minor) bump release to 5.25.0
  CHANGELOG.md
  VERSION
Labels: FUN

#639 🐛(cli) autodetect if we are in a terminal
  CHANGELOG.md
  bin/arnold
Labels: bug

#641 🐛(core) trim templates before checking if we should ignore them
  apps/forum/templates/services/mongodb/deploy.yml.j2
  tasks/filter_empty_templates_for_app.yml
Labels: bug

#645 🐛(apps) fix syntax error in nginx deployment templates
  apps/ashley/templates/services/nginx/deploy.yml.j2
  apps/edxapp/templates/services/nginx/deploy.yml.j2
  apps/richie/templates/services/nginx/deploy.yml.j2
Labels: bug, needs review

#648 ✨(cli) add a `pause` and `resume` command to arnold CLI
  bin/arnold
Labels: feature, needs review
