Repository openfun/arnold, pull requests merged in 2021-01, with the labels that each got.

#590 💥(apps) fix typos in setting names: `withelist` vs `whitelist`
  CHANGELOG.md
  apps/ashley/templates/services/nginx/configs/ashley.conf.j2
  apps/ashley/vars/all/main.yml
  apps/edxapp/templates/services/nginx/configs/cms.conf.j2
  apps/edxapp/templates/services/nginx/configs/lms.conf.j2
  apps/edxapp/vars/all/main.yml
  apps/edxec/templates/services/nginx/configs/edxec.conf.j2
  apps/edxec/vars/all/main.yml
  apps/learninglocker/templates/services/nginx/configs/default.conf.j2
  apps/learninglocker/vars/all/main.yml
  apps/marsha/templates/services/nginx/configs/marsha.conf.j2
  apps/marsha/vars/all/main.yml
  apps/moodlenet/vars/all/main.yml
  apps/nextcloud/templates/services/nginx/configs/nextcloud.conf.j2
  apps/nextcloud/vars/all/main.yml
  apps/richie/templates/services/nginx/configs/richie.conf.j2
  apps/richie/vars/all/main.yml
Labels: bug

#592 ✨(cli) improve container volumes management
  CHANGELOG.md
  bin/arnold
Labels: feature

#593 🐛(project) fix Makefile's automated help
  Makefile
Labels: bug

#596 🔖(minor) bump release to 5.24.0
  CHANGELOG.md
  VERSION
  bin/arnold
Labels: FUN, needs review
