Repository openfun/arnold, pull requests merged in 2022-01, with the labels that each got.

#711 🔧(marsha) add x-forwarded-for header in nginx configuration
  CHANGELOG.md
  apps/marsha/templates/services/nginx/configs/marsha.conf.j2
Labels: improvement

#715 ⬆️(project) upgrade ansible-lint to 5.3.2
  requirements/development.txt
Labels: dependencies

#717 🐛(kibana) fix replicas load balancing configuration
  CHANGELOG.md
  apps/kibana/templates/services/app/configs/kibana.yml.j2
  apps/kibana/templates/services/app/deploy.yml.j2
  apps/kibana/templates/services/app/secret.yml.j2
  apps/kibana/vars/vault/main.yml.j2
  group_vars/customer/eugene/ci/secrets/kibana.vault.yml
Labels: bug, needs review

#719 🔖(minor) bump release to 6.9.0
  CHANGELOG.md
  VERSION
Labels: needs review, FUN

#713 ✨(marsha) configure nginx to handle websocket
  CHANGELOG.md
  apps/marsha/templates/services/nginx/configs/marsha.conf.j2
Labels: feature request

#721 ✨(marsha) Use unprivileged image provided by Nginx
  CHANGELOG.md
  apps/marsha/vars/all/main.yml
Labels: improvement
